name: Update README

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is merged
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged
        run: echo "Pull request merged, triggering update..."

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Run updateReadme script
        run: node updateReadme.js

      - name: Merge contributors from pull request and remove contributors.json
        run: |
          new_contributors=$(jq -r '.[] | "* [\(.name)](\(.portfolio))"' contributors.json)
          existing_contributors=$(awk '/<!-- CONTRIBUTORS_START -->/,/<!-- CONTRIBUTORS_END -->/' README.md | grep -vE "<!-- CONTRIBUTORS_(START|END) -->")
          all_contributors=$(echo -e "$existing_contributors\n$new_contributors" | sort | uniq)
          echo "$all_contributors" > temp.txt
          sed -i -e '/<!-- CONTRIBUTORS_START -->/,/<!-- CONTRIBUTORS_END -->/{ /<!-- CONTRIBUTORS_START -->/{p; r temp.txt
          }; /<!-- CONTRIBUTORS_END -->/p; d }' README.md

      - name: Remove contributors.json
        run: |
          rm contributors.json

      - name: Set Git user identity
        run: |
          git config --local user.email "asinhonore823@gmail.com"
          git config --local user.name "Asin-Junior-Honore"

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update README with merged contributors"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
