name: Update README

on:
  pull_request:
    types: [closed]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged # Only run when the pull request is merged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Merge contributors from pull request
        run: |

          new_contributors=$(jq -s 'flatten | unique_by(.name)' contributors.json)


          existing_contributors=$(awk '/<!-- CONTRIBUTORS_START -->/,/<!-- CONTRIBUTORS_END -->/' README.md | grep -vE "<!-- CONTRIBUTORS_(START|END) -->")


          all_contributors=$(echo -e "$existing_contributors\n$new_contributors" | sort | uniq)

          sed -i -e "/<!-- CONTRIBUTORS_START -->/,/<!-- CONTRIBUTORS_END -->/c\\
          <!-- CONTRIBUTORS_START -->\\
          $all_contributors\\
          <!-- CONTRIBUTORS_END -->" README.md

      - name: Set Git user identity
        run: |
          git config --local user.email "asinhonore823@gmail.com"
          git config --local user.name "Asin-Junior-Honore"

      - name: Commit changes
        run: |
          git add README.md
          git commit -m "Update README with merged contributors"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
