name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Clone the private repository using a personal access token
      - name: Clone private repository
        run: |
          git clone https://github.com/Asin-Junior-Honore/privateupdate.git
          mv privateupdate/* .
          rm -rf privateupdate
        env:
          GITHUB_TOKEN: ${{ secrets.newtoken }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Run updateReadme script
        run: node updateReadme.js

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Automatically update README.md"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.newtoken }}
