name: Update README

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.merged || github.ref == 'refs/heads/main' # Run when PR is merged or when pushing to main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Merge contributors from pull request
        run: |
          new_contributors=$(jq -r '.[] | "* [\(.name)](\(.portfolio))"' contributors.json)
          existing_contributors=$(awk '/<!-- CONTRIBUTORS_START -->/,/<!-- CONTRIBUTORS_END -->/' README.md | grep -vE "<!-- CONTRIBUTORS_(START|END) -->")
          all_contributors=$(echo -e "$existing_contributors\n$new_contributors" | sort | uniq)
          echo "$all_contributors" > temp.txt
          sed -i -e '/<!-- CONTRIBUTORS_START -->/,/<!-- CONTRIBUTORS_END -->/{ /<!-- CONTRIBUTORS_START -->/{p; r temp.txt
          }; /<!-- CONTRIBUTORS_END -->/p; d }' README.md  

      - name: Set Git user identity
        run: |
          git config --local user.email "asinhonore823@gmail.com"
          git config --local user.name "Asin-Junior-Honore"

      - name: Commit changes
        run: |
          git add README.md contributors.json
          git commit -m "Update README with merged contributors"
          git push origin HEAD:main
          rm contributors.json  # Delete contributors.json file after committing changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
