name: Update README

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is merged
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged
        run: echo "Pull request merged, triggering update..."

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Run updateReadme script
        run: node updateReadme.js

      - name: Remove contributors.json
        run: |
          rm contributors.json

      - name: Set Git user identity
        run: |
          git config --local user.email "${{ secrets.MY_GITHUB_EMAIL }}"
          git config --local user.name "${{ secrets.MY_GITHUB_USERNAME }}"

      - name: Commit changes
        run: |
          git add .
          git commit -m "Remove contributors.json file"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
